<?php

use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * Redirect users after calcel
 *
 */
function eereMfa_cancel() {
  $url = $_GET['destination'] = getBaseUrl().'user/login';
  $response = new RedirectResponse($url);
  return $response->send();
}

function getBaseUrl() 
{
    // output: /myproject/index.php
    $currentPath = $_SERVER['PHP_SELF']; 
    
    // output: Array ( [dirname] => /myproject [basename] => index.php [extension] => php [filename] => index ) 
    $pathInfo = pathinfo($currentPath); 
    
    // output: localhost
    $hostName = $_SERVER['HTTP_HOST']; 
    
    // output: http://
    $protocol = strtolower(substr($_SERVER["SERVER_PROTOCOL"],0,5))=='https://'?'https://':'http://';
    
    // return: http://localhost/myproject/
    return $protocol.$hostName.$pathInfo['dirname']."/";
}

function eereMfa_page_attachments(array &$attachments) {

  $attachments['#attached']['library'][] = 'eereMfa/lrv';

}
